title: Trump ran a campaign based on intelligence security. That’s not how he’s governing.
url: https://www.washingtonpost.com/news/politics/wp/2017/02/13/trump-ran-a-campaign-based-on-intelligence-security-thats-not-how-hes-governing/
quote: The picture that’s painted is one that runs contrary to the arguments Trump made on the campaign trail. While running for the presidency, cybersecurity and the risk of compromise were cardinal sins, necessitating that he be given the most powerful position in America. Now that he’s attained that position, though, his attitude toward security seems a bit more lax.
tags:
 - Security
 - But Her Emails
