title: Secrecy surrounds White House cybersecurity staff shakeup
url: http://www.zdnet.com/article/white-house-chief-information-security-officer-departs/
desc: "“However, one source said it's because the remaining staff have “targets on their back” and are afraid of speaking out, calling the actions a “witch hunt” for former Obama appointees. Accusations of poor management were said to be reasons or excuses for his forced departure amid what was described as a “toxic” working environment.”"
tags:
 - Cyber
 - Glorious Leader
